import { describe, expect, it } from "vitest";
import {
  reportToMarkdown,
  reportToJSON,
  reportToHTML,
  slugify,
  generateDeliveryReceipt,
  type ExportReport,
} from "./exportReport";
import type { Project } from "@/types";

function makeReport(overrides: Partial<ExportReport> = {}): ExportReport {
  const project: Project = {
    id: "proj1",
    title: "Spring Campaign",
    status: "active",
    client: "Acme Co",
    category: "advertising",
    brief_text: "A brief.",
    production_goal: "10 hero shots.",
    tags: [],
    created_at: "2026-01-01T00:00:00.000Z",
    updated_at: "2026-01-01T00:00:00.000Z",
  };
  return {
    generated_at: "2026-06-01T12:00:00.000Z",
    project,
    prompts: [],
    results: [],
    references: [],
    deliverables: [],
    shots: [],
    suggestions: [],
    ...overrides,
  };
}

// ─── slugify ──────────────────────────────────────────────────

describe("slugify", () => {
  it("lowercases and replaces spaces with hyphens", () => {
    expect(slugify("Spring Campaign 2026")).toBe("spring-campaign-2026");
  });

  it("strips special characters", () => {
    expect(slugify("My Project: V2!")).toBe("my-project-v2");
  });

  it("trims leading/trailing hyphens", () => {
    expect(slugify("  hello world  ")).toBe("hello-world");
  });
});

// ─── Markdown export ──────────────────────────────────────────

describe("reportToMarkdown", () => {
  it("includes the project title as h1", () => {
    const md = reportToMarkdown(makeReport());
    expect(md).toContain("# Spring Campaign");
  });

  it("includes client and category", () => {
    const md = reportToMarkdown(makeReport());
    expect(md).toContain("Acme Co");
    expect(md).toContain("advertising");
  });

  it("includes brief text", () => {
    const md = reportToMarkdown(makeReport());
    expect(md).toContain("A brief.");
  });

  it("includes winning prompts section when winners exist", () => {
    const md = reportToMarkdown(makeReport({
      prompts: [{
        id: "p1", title: "Hero Shot", provider: "midjourney",
        rating: 9, is_winner: true, is_failed: false,
        prompt_text: "a product on white bg", ai_look_risk: 2,
        version: 1, created_at: "2026-01-01T00:00:00.000Z",
      }],
    }));
    expect(md).toContain("Winning Prompts");
    expect(md).toContain("Hero Shot");
    expect(md).toContain("a product on white bg");
  });

  it("omits winning prompts section when none exist", () => {
    const md = reportToMarkdown(makeReport({
      prompts: [{
        id: "p1", title: "Draft", provider: "dalle",
        rating: 5, is_winner: false, is_failed: false,
        prompt_text: "draft prompt", ai_look_risk: 4,
        version: 1, created_at: "2026-01-01T00:00:00.000Z",
      }],
    }));
    expect(md).not.toContain("## Winning Prompts");
  });

  it("includes failed directions when failed prompts exist", () => {
    const md = reportToMarkdown(makeReport({
      prompts: [{
        id: "p1", title: "Bad Direction", provider: "midjourney",
        rating: 2, is_winner: false, is_failed: true,
        prompt_text: "bad prompt", failure_notes: "too synthetic",
        ai_look_risk: 9, version: 1, created_at: "2026-01-01T00:00:00.000Z",
      }],
    }));
    expect(md).toContain("Failed Directions");
    expect(md).toContain("Bad Direction");
    expect(md).toContain("too synthetic");
  });

  it("includes suggestions when present", () => {
    const md = reportToMarkdown(makeReport({
      suggestions: ["Next action: craft a variation", "Add style references"],
    }));
    expect(md).toContain("Recommendations");
    expect(md).toContain("craft a variation");
  });

  it("ends with Framecraft footer", () => {
    const md = reportToMarkdown(makeReport());
    expect(md).toContain("Generated by Framecraft");
  });
});

// ─── JSON export ──────────────────────────────────────────────

describe("reportToJSON", () => {
  it("produces valid JSON", () => {
    const json = reportToJSON(makeReport());
    expect(() => JSON.parse(json)).not.toThrow();
  });

  it("round-trips project title", () => {
    const json = reportToJSON(makeReport());
    const parsed = JSON.parse(json) as ExportReport;
    expect(parsed.project.title).toBe("Spring Campaign");
  });

  it("preserves generated_at timestamp", () => {
    const json = reportToJSON(makeReport());
    const parsed = JSON.parse(json) as ExportReport;
    expect(parsed.generated_at).toBe("2026-06-01T12:00:00.000Z");
  });
});

// ─── HTML export ──────────────────────────────────────────────

describe("reportToHTML", () => {
  it("is a valid HTML document with doctype", () => {
    const html = reportToHTML(makeReport());
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("<html");
    expect(html).toContain("</html>");
  });

  it("includes the project title", () => {
    const html = reportToHTML(makeReport());
    expect(html).toContain("Spring Campaign");
  });

  it("escapes HTML special characters in project title", () => {
    const html = reportToHTML(makeReport({
      project: {
        ...makeReport().project,
        title: "Project <Test> & 'Demo'",
      },
    }));
    expect(html).toContain("&lt;Test&gt;");
    expect(html).toContain("&amp;");
    expect(html).not.toContain("<Test>");
  });

  it("includes client name", () => {
    const html = reportToHTML(makeReport());
    expect(html).toContain("Acme Co");
  });

  it("includes brief text", () => {
    const html = reportToHTML(makeReport());
    expect(html).toContain("A brief.");
  });

  it("marks high-risk prompts", () => {
    const html = reportToHTML(makeReport({
      prompts: [{
        id: "p1", title: "High Risk Prompt", provider: "midjourney",
        rating: 4, is_winner: false, is_failed: false,
        prompt_text: "risky", ai_look_risk: 8,
        version: 1, created_at: "2026-01-01T00:00:00.000Z",
      }],
    }));
    expect(html).toContain("risk-high");
    expect(html).toContain("8/10");
  });
});

describe("Shot sequence in exports", () => {
  const shotsReport = makeReport({
    shots: [
      {
        id: "s1", sort_order: 0, shot_type: "hero", label: "Hero wide",
        prompt_id: "p1", prompt_title: "Fashion Hero",
        result_id: "r1", result_score: 4, result_is_winner: true,
      },
      {
        id: "s2", sort_order: 1, shot_type: "detail", label: "Texture close",
        prompt_id: undefined, prompt_title: undefined,
        result_id: undefined, result_score: undefined,
      },
    ],
  });

  it("includes Shot Sequence section in Markdown", () => {
    const md = reportToMarkdown(shotsReport);
    expect(md).toContain("## Shot Sequence");
    expect(md).toContain("Hero wide");
    expect(md).toContain("Fashion Hero");
  });

  it("shows completion stats in Markdown shot section", () => {
    const md = reportToMarkdown(shotsReport);
    expect(md).toContain("1 linked to prompt");
  });

  it("includes Shot Sequence table in HTML", () => {
    const html = reportToHTML(shotsReport);
    expect(html).toContain("Shot Sequence");
    expect(html).toContain("Hero wide");
  });

  it("includes shots array in JSON export", () => {
    const json = reportToJSON(shotsReport);
    const parsed = JSON.parse(json) as { shots: unknown[] };
    expect(parsed.shots).toHaveLength(2);
  });
});

describe("generateDeliveryReceipt", () => {
  const deliveryReport = makeReport({
    prompts: [{
      id: "p1", title: "Hero Shot", provider: "midjourney",
      rating: 5, is_winner: true, is_failed: false,
      prompt_text: "product on white cinematic --ar 16:9", ai_look_risk: 2,
      version: 1, created_at: "2026-01-01T00:00:00.000Z",
    }],
    shots: [{
      id: "s1", sort_order: 0, shot_type: "hero", label: "Hero wide",
      prompt_id: "p1", prompt_title: "Hero Shot",
      result_id: "r1", result_score: 5, result_is_winner: true,
    }],
  });

  it("includes project title and client in receipt", () => {
    const receipt = generateDeliveryReceipt(deliveryReport, "2026-06-27");
    expect(receipt).toContain("Spring Campaign");
    expect(receipt).toContain("Acme Co");
    expect(receipt).toContain("2026-06-27");
  });

  it("includes winning prompt text", () => {
    const receipt = generateDeliveryReceipt(deliveryReport, "2026-06-27");
    expect(receipt).toContain("product on white cinematic --ar 16:9");
    expect(receipt).toContain("1 winning prompt");
  });

  it("includes shot sequence table", () => {
    const receipt = generateDeliveryReceipt(deliveryReport, "2026-06-27");
    expect(receipt).toContain("Shot Sequence");
    expect(receipt).toContain("Hero wide");
    expect(receipt).toContain("★ Winner");
  });
});
